// ───────────────────────────────────────────────
// Fake data for the Recruitment Dashboard demo
// ───────────────────────────────────────────────

import type {
  Candidate,
  Recruiter,
} from "@/types";

/** Current logged-in recruiter */
export const currentRecruiter: Recruiter = {
  id: "rec-1",
  name: "Faizan Ahmed",
  email: "faizan@hireflow.io",
  avatarUrl: "/avatars/faizan.jpg",
};

/** All recruiters for the dropdown */
export const recruiters: Recruiter[] = [
  currentRecruiter,
  { id: "rec-2", name: "Priya Sharma", email: "priya@hireflow.io", avatarUrl: "/avatars/priya.jpg" },
  { id: "rec-3", name: "Sarah Jenkins", email: "sarah@hireflow.io", avatarUrl: "/avatars/sarah.jpg" },
];

/** Demo candidates */
export const candidates: Candidate[] = [
  {
    id: "cand-1",
    name: "Arjun Mehta",
    title: "Senior Software Engineer",
    email: "arjun.m@example.com",
    phone: "+91 98765 43210",
    linkedIn: "linkedin.com/in/arjunmehta",
    avatarUrl: "/avatars/arjun.jpg",
    location: "San Francisco, CA",
    workType: "Full-time",
    workMode: "Remote",
    skills: ["React", "Node.js", "Python", "AWS", "Docker"],
    noticePeriod: "30 Days (Negotiable)",
    currentCtc: "₹24,00,000 LPA",
    expectedCtc: "₹32,00,000 LPA",
    yearsOfExperience: 8,
    assignedRecruiter: "Faizan Ahmed",
    notes: "Strong backend candidate. Good communication skills. Prefers remote roles.",
    createdAt: "2023-09-15",
    applications: [
      {
        id: "app-1",
        jobTitle: "Senior Backend Engineer",
        company: "TechNova Solutions",
        workMode: "Remote",
        source: "LinkedIn",
        jobPostingUrl: "https://example.com/job/101",
        status: "In Interview",
        appliedDate: "2023-10-10",
        hiringManager: "Sarah Jenkins",
        tags: ["React", "Node.js", "AWS"],
        nextAction: "Awaiting Feedback",
        rounds: [
          {
            id: "r-1",
            roundNumber: 1,
            title: "Round 1: Confirmation Call",
            roundType: "Confirmation Call",
            date: "2023-10-24",
            time: "11:00 AM",
            timezone: "IST",
            duration: "30 mins",
            mode: "Phone",
            vcReceiver: "",
            frontendCoordinator: "Priya Sharma",
            lipsyncQuality: "Good",
            feedback: "Candidate demonstrated strong understanding of Node.js event loop and async patterns.",
            status: "Cleared",
          },
          {
            id: "r-2",
            roundNumber: 2,
            title: "Round 2: Technical Assessment",
            roundType: "Technical Interview",
            date: "2023-10-28",
            time: "03:00 PM",
            timezone: "IST",
            duration: "60 mins",
            mode: "Video Call (Google Meet)",
            vcReceiver: "arjun.m@example.com",
            frontendCoordinator: "David Chen",
            lipsyncQuality: "Good",
            feedback: "",
            status: "Pending",
          },
        ],
      },
      {
        id: "app-2",
        jobTitle: "Frontend Lead",
        company: "Google",
        workMode: "Hybrid",
        source: "LinkedIn",
        jobPostingUrl: "https://example.com/job/102",
        status: "Interview Scheduled",
        appliedDate: "2023-10-05",
        tags: ["LinkedIn", "React", "Node.js", "TypeScript"],
        nextAction: "Awaiting Feedback",
        rounds: [],
      },
      {
        id: "app-3",
        jobTitle: "Senior Engineer",
        company: "Amazon",
        workMode: "Onsite",
        source: "Referral",
        jobPostingUrl: "https://example.com/job/103",
        status: "Offer Received",
        appliedDate: "2023-09-20",
        tags: ["Referral", "AWS", "Node.js", "DynamoDB"],
        nextAction: "Negotiation",
        rounds: [],
      },
    ],
  },
  {
    id: "cand-2",
    name: "John Doe",
    title: "Full Stack Developer",
    email: "john.doe@example.com",
    phone: "+1 (555) 000-0000",
    linkedIn: "linkedin.com/in/johndoe",
    avatarUrl: "/avatars/john.jpg",
    location: "New York, USA",
    workType: "Full-time",
    workMode: "Hybrid",
    skills: ["Java", "Salesforce", "Spring Boot", "REST APIs"],
    noticePeriod: "Immediate",
    currentCtc: "₹18,00,000 LPA",
    expectedCtc: "₹22,00,000 LPA",
    yearsOfExperience: 5,
    assignedRecruiter: "Faizan Ahmed",
    notes: "",
    createdAt: "2023-11-01",
    applications: [
      {
        id: "app-4",
        jobTitle: "Salesforce Developer",
        company: "Deloitte",
        workMode: "Hybrid",
        source: "Naukri",
        status: "Technical Interview",
        appliedDate: "2023-11-10",
        tags: ["Java", "Salesforce"],
        nextAction: "Schedule Round 2",
        rounds: [
          {
            id: "r-3",
            roundNumber: 1,
            title: "Round 1: HR Screen",
            roundType: "HR Screen",
            date: "2026-03-07",
            time: "02:00 PM",
            timezone: "EST",
            duration: "30 mins",
            mode: "Phone",
            vcReceiver: "",
            frontendCoordinator: "",
            lipsyncQuality: "Good",
            feedback: "Good cultural fit. Proceed to technical.",
            status: "Cleared",
          },
        ],
      },
    ],
  },
  {
    id: "cand-3",
    name: "Jane Smith",
    title: "Backend Engineer",
    email: "jane.smith@example.com",
    phone: "+1 (555) 111-2222",
    linkedIn: "linkedin.com/in/janesmith",
    avatarUrl: "/avatars/jane.jpg",
    location: "London, UK",
    workType: "Full-time",
    workMode: "Remote",
    skills: ["Java", "Spring Boot", "Microservices", "Kafka"],
    noticePeriod: "60 Days",
    currentCtc: "£55,000",
    expectedCtc: "£70,000",
    yearsOfExperience: 6,
    assignedRecruiter: "Priya Sharma",
    notes: "Open to relocation. Strong system design skills.",
    createdAt: "2023-11-05",
    applications: [
      {
        id: "app-5",
        jobTitle: "Platform Engineer",
        company: "Spotify",
        workMode: "Remote",
        source: "LinkedIn",
        status: "HR Screen",
        appliedDate: "2023-11-15",
        tags: ["Java", "Spring Boot", "Kafka"],
        nextAction: "HR follow up",
        rounds: [
          {
            id: "r-4",
            roundNumber: 1,
            title: "Round 1: Initial Screen",
            roundType: "HR Screen",
            date: "2026-03-08",
            time: "10:00 AM",
            timezone: "GMT",
            duration: "30 mins",
            mode: "Video Call (Google Meet)",
            vcReceiver: "jane.smith@example.com",
            frontendCoordinator: "",
            lipsyncQuality: "Good",
            feedback: "",
            status: "Pending",
          },
        ],
      },
    ],
  },
  {
    id: "cand-4",
    name: "Alex Rivera",
    title: "Salesforce Architect",
    email: "alex.rivera@example.com",
    phone: "+1 (555) 333-4444",
    linkedIn: "linkedin.com/in/alexrivera",
    avatarUrl: "/avatars/alex.jpg",
    location: "Austin, TX",
    workType: "Contract",
    workMode: "Remote",
    skills: ["Salesforce", "Apex", "Lightning", "Integration"],
    noticePeriod: "2 Weeks",
    currentCtc: "$120,000",
    expectedCtc: "$150,000",
    yearsOfExperience: 10,
    assignedRecruiter: "Faizan Ahmed",
    notes: "Very experienced. Looking for architect-level roles only.",
    createdAt: "2023-11-10",
    applications: [
      {
        id: "app-6",
        jobTitle: "Lead Salesforce Architect",
        company: "Accenture",
        workMode: "Hybrid",
        source: "Referral",
        status: "Offer Stage",
        appliedDate: "2023-11-01",
        tags: ["Salesforce", "Apex"],
        nextAction: "Offer letter pending",
        rounds: [
          {
            id: "r-5",
            roundNumber: 1,
            title: "Round 1: Technical Interview",
            roundType: "Technical Interview",
            date: "2026-03-09",
            time: "04:00 PM",
            timezone: "CST",
            duration: "60 mins",
            mode: "Video Call (Zoom)",
            vcReceiver: "alex.rivera@example.com",
            frontendCoordinator: "",
            lipsyncQuality: "Excellent",
            feedback: "Outstanding system design. Strong Salesforce knowledge.",
            status: "Cleared",
          },
        ],
      },
    ],
  },
  {
    id: "cand-5",
    name: "Sneha Kapoor",
    title: "DevOps Engineer",
    email: "sneha.k@example.com",
    phone: "+91 87654 32100",
    linkedIn: "linkedin.com/in/snehakapoor",
    avatarUrl: "/avatars/sneha.jpg",
    location: "Bangalore, India",
    workType: "Full-time",
    workMode: "Hybrid",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD"],
    noticePeriod: "90 Days",
    currentCtc: "₹20,00,000 LPA",
    expectedCtc: "₹28,00,000 LPA",
    yearsOfExperience: 4,
    assignedRecruiter: "Sarah Jenkins",
    notes: "Good at infra automation. Prefers product companies.",
    createdAt: "2023-11-12",
    applications: [],
  },
];

/** Helper: get candidate by ID */
export function getCandidateById(id: string): Candidate | undefined {
  return candidates.find((c) => c.id === id);
}

/** Dashboard stats (computed from fake data) */
export const dashboardStats = {
  activeCandidates: 18,
  activeCandidatesChange: "+12%",
  interviewsThisWeek: 5,
  interviewsNote: "On schedule",
  offersPending: 2,
  offersNote: "Action required",
  goalProgress: 75,
};
